name: Format Version Workflow

on:
  workflow_call:
    inputs:
      sub-repo:
        type: string
        description: 'The sub-repo to format the version for'
        required: false
    # outputs:
    #   formatted-version:
    #     description: 'The formatted version'
    #     value: ${{ steps.format-version.outputs.formatted-version }}

jobs:
  format-version:
    name: Format Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version.json and set environment variables
        id: read-version
        run: |
          echo "YEAR=$(jq -r '.year' version.json)" >> $GITHUB_ENV
          echo "MONTH=$(jq -r '.month' version.json)" >> $GITHUB_ENV

      - name: Print version
        run: |
          echo "YEAR=$YEAR"
          echo "MONTH=$MONTH"

      - name: Print sub-repo
        run: |
          echo "Sub-repo: ${{ inputs.sub-repo }}"

      # - name: Format version
      #   id: format-version
      #   run: |
      #     echo "formatted-version=v$YEAR.$MONTH" >> $GITHUB_OUTPUT
